### ISSUE TITLE
Error when accessing a broker on brokers page.

### ISSUE THREAD

**Issue by davidballano** [cloudhut/kowl#226]
Hello, i was trying Kowl. it is pretty slick! good job!
for some reason when accessing the brokers page and clicking in one of the brokers i get this error below:

this is how i am running it:
`docker run -p 8080:8080 -e KAFKA_BROKERS=x.x.x.x:9092 -e KAFKA_TLS_ENABLED=false -e KAFKA_SASL_ENABLED=false quay.io/cloudhut/kowl:master
`

```
Type:
TypeError

Message:
Cannot read property 'split' of null

Stack (Decoded):
split (components/pages/topics/Tab.Config.tsx:276:32)
DataValue (components/pages/topics/Tab.Config.tsx:242:12)
e (components/pages/brokers/Broker.List.tsx:182:39)
map (components/pages/brokers/Broker.List.tsx:180:21)
allowStateChanges (../node_modules/mobx/lib/mobx.module.js:978:14)
r (http://localhost:8080/static/js/2.49dcbd54.chunk.js:2:61026)
trackDerivedFunction (../node_modules/mobx/lib/mobx.module.js:761:23)
track (../node_modules/mobx/lib/mobx.module.js:1795:21)
r (http://localhost:8080/static/js/2.49dcbd54.chunk.js:2:60974)

Stack (Raw):
TypeError: Cannot read property 'split' of null
    at G (http://localhost:8080/static/js/main.d9efba3a.chunk.js:1:14679)
    at F (http://localhost:8080/static/js/main.d9efba3a.chunk.js:1:14271)
    at http://localhost:8080/static/js/main.d9efba3a.chunk.js:1:123532
    at Array.map (<anonymous>)
    at n.value (http://localhost:8080/static/js/main.d9efba3a.chunk.js:1:123442)
    at Ee (http://localhost:8080/static/js/2.49dcbd54.chunk.js:2:13680)
    at http://localhost:8080/static/js/2.49dcbd54.chunk.js:2:61026
    at ue (http://localhost:8080/static/js/2.49dcbd54.chunk.js:2:11786)
    at e.track (http://localhost:8080/static/js/2.49dcbd54.chunk.js:2:23144)
    at n.s [as render] (http://localhost:8080/static/js/2.49dcbd54.chunk.js:2:60974)

Components:

    in n
    in n
    in td
    in Cell
    in tr
    in K
    in BodyRow
    in tbody
    in Unknown
    in table
    in div
    in div
    in Unknown
    in Unknown
    in div
    in Ne
    in div
    in div
    in f
    in div
    in Er
    in div
    in n
    in div
    in ForwardRef
    in n
    in t
    in t
    in Ci
    in ki
    in Lt
    in n
    in main
    in S
    in Content
    in section
    in n
    in Layout
    in s
    in section
    in n
    in Layout
    in t
    in t
    in n
    in r
    in t
    in t

Environment:
NODE_ENV       : production
GIT_SHA        : b752ef6735b35c0a5e290070742bc51c76eacbf9
GIT_REF        : master
TIMESTAMP      : 1619543648
BUILT_FROM_PUSH: true
appName        : Kowl

Location:
Protocol: http:
Path    : /brokers
Search  : 
Hash    : 


```

**Comment by weeco** [comment]
Hey David,
thank you for the warm words. Regarding the issue you are facing: This happens when the backend fails to get a config from that broker and then sends a "null" object to the frontend without setting an appropriate error. We've seen this as well, but I have yet to figure out why we don't receive an error.

Regardless we will find a solution for that. Thanks for reporting :).

**Comment by Dionakra** [comment]
Hi, 

I just got the same message. In our case, I am running kowl with a user with not so many permissions on the cluster, so the user can't see ACLs and more things. I was about to open an issue but saw this.

Maybe the error is related to the user not having enough permissions to access certain information on the view? At least I know the users is quite capped on what it can do, so it might be a lead to the problem.

PS: Thanks for the software, kowl is pretty amazing!

**Comment by weeco** [comment]
@Dionakra Do you have any logs in the backend when that happens? I'll double check the code in the meantime

**Comment by Dionakra** [comment]
Sure, I just put the logLevel to DEBUG. Here you have:

```
{"level":"debug","ts":"2021-09-09T09:27:12.929Z","msg":"requested file not found","requestURI":"/brokers","path":"/brokers"}
{"level":"debug","ts":"2021-09-09T09:27:13.202Z","msg":"wrote ApiVersions v3","source":"kafka_client","broker":-2147483648,"bytes_written":28,"write_wait":0.000014066,"time_to_write":0.000046232,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.240Z","msg":"wrote Metadata v9","source":"kafka_client","broker":3,"bytes_written":24,"write_wait":0.000005639,"time_to_write":0.000029448,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.240Z","msg":"wrote Metadata v9","source":"kafka_client","broker":2,"bytes_written":24,"write_wait":0.000010735,"time_to_write":0.000028017,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.240Z","msg":"wrote Metadata v9","source":"kafka_client","broker":1,"bytes_written":24,"write_wait":0.000026068,"time_to_write":0.000039374,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.240Z","msg":"wrote ApiVersions v3","source":"kafka_client","broker":-2147483648,"bytes_written":28,"write_wait":0.000009297,"time_to_write":0.000058296,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.328Z","msg":"read ApiVersions v3","source":"kafka_client","broker":-2147483648,"bytes_read":481,"read_wait":0.000011915,"time_to_read":0.126037622,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.332Z","msg":"read ApiVersions v3","source":"kafka_client","broker":-2147483648,"bytes_read":481,"read_wait":0.088040758,"time_to_read":0.003914205,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.528Z","msg":"read Metadata v9","source":"kafka_client","broker":3,"bytes_read":97716,"read_wait":0.000005821,"time_to_read":0.288058911,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.529Z","msg":"sharded request","source":"kafka_client","destinations":["2","3","1"]}
{"level":"debug","ts":"2021-09-09T09:27:13.529Z","msg":"wrote DescribeLogDirs v2","source":"kafka_client","broker":1,"bytes_written":21,"write_wait":0.000015005,"time_to_write":0.000031533,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.529Z","msg":"wrote DescribeLogDirs v2","source":"kafka_client","broker":2,"bytes_written":21,"write_wait":0.000009313,"time_to_write":0.000032899,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.529Z","msg":"wrote DescribeLogDirs v2","source":"kafka_client","broker":3,"bytes_written":21,"write_wait":0.000009698,"time_to_write":0.000028551,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.577Z","msg":"read Metadata v9","source":"kafka_client","broker":1,"bytes_read":97716,"read_wait":0.000002069,"time_to_read":0.336640863,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.578Z","msg":"sharded request","source":"kafka_client","destinations":["2"]}
{"level":"debug","ts":"2021-09-09T09:27:13.578Z","msg":"sharded request","source":"kafka_client","destinations":["3"]}
{"level":"debug","ts":"2021-09-09T09:27:13.578Z","msg":"sharded request","source":"kafka_client","destinations":["1"]}
{"level":"debug","ts":"2021-09-09T09:27:13.578Z","msg":"wrote DescribeConfigs v3","source":"kafka_client","broker":2,"bytes_written":32,"write_wait":0.000013235,"time_to_write":0.000047724,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.578Z","msg":"wrote DescribeConfigs v3","source":"kafka_client","broker":3,"bytes_written":32,"write_wait":0.00000855,"time_to_write":0.000039264,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.578Z","msg":"wrote DescribeConfigs v3","source":"kafka_client","broker":1,"bytes_written":32,"write_wait":0.000007309,"time_to_write":0.000027251,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.584Z","msg":"read DescribeLogDirs v2","source":"kafka_client","broker":3,"bytes_read":15,"read_wait":0.000011297,"time_to_read":0.05440581,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.584Z","msg":"read DescribeLogDirs v2","source":"kafka_client","broker":1,"bytes_read":15,"read_wait":0.048487221,"time_to_read":0.006773184,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.628Z","msg":"read DescribeConfigs v3","source":"kafka_client","broker":1,"bytes_read":57,"read_wait":0.006638727,"time_to_read":0.043108399,"err":null}
{"level":"warn","ts":"2021-09-09T09:27:13.628Z","msg":"failed to describe broker config","broker_id":1,"error":"CLUSTER_AUTHORIZATION_FAILED: Cluster authorization failed."}
{"level":"debug","ts":"2021-09-09T09:27:13.628Z","msg":"read DescribeConfigs v3","source":"kafka_client","broker":3,"bytes_read":57,"read_wait":0.005893565,"time_to_read":0.044482994,"err":null}
{"level":"warn","ts":"2021-09-09T09:27:13.628Z","msg":"failed to describe broker config","broker_id":3,"error":"CLUSTER_AUTHORIZATION_FAILED: Cluster authorization failed."}
{"level":"debug","ts":"2021-09-09T09:27:13.660Z","msg":"read Metadata v9","source":"kafka_client","broker":2,"bytes_read":97716,"read_wait":0.000002358,"time_to_read":0.419956438,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.661Z","msg":"read DescribeLogDirs v2","source":"kafka_client","broker":2,"bytes_read":15,"read_wait":0.131792232,"time_to_read":0.000009917,"err":null}
{"level":"debug","ts":"2021-09-09T09:27:13.661Z","msg":"read DescribeConfigs v3","source":"kafka_client","broker":2,"bytes_read":57,"read_wait":0.083194404,"time_to_read":0.00000519,"err":null}
{"level":"warn","ts":"2021-09-09T09:27:13.661Z","msg":"failed to describe broker config","broker_id":2,"error":"CLUSTER_AUTHORIZATION_FAILED: Cluster authorization failed."}

```

**Comment by weeco** [comment]
Thanks @Dionakra ,
last question: What Kowl version do you use? :)

**Comment by Dionakra** [comment]
I am pulling from master using docker, so I might have the image cached, but the footer shows the following:

Kowl CI
5ff4360
(built Mon May 17 2021)

**Comment by weeco** [comment]
@Dionakra Thank you for all the information, I found the issue and committed a fix :). Let me know if it works with the latest version  (docker image is being built right now) :).
