### ISSUE TITLE
Schema registry rendering error

### ISSUE THREAD

**Issue by MigTremblay** [cloudhut/kowl#280]
When trying to access the schema registry I'm getting this error.
It started happening when I made a field use another schema as type.

```
Message:
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bfields%2C%20name%2C%20type%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stack:
at Ei (http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1231151)
at p (http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1232792)
at y (http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1233907)
at http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1235995
at Ta (http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1245521)
at vc (http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1286346)
at lu (http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1276558)
at cu (http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1276483)
at Zc (http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1273492)
at http://localhost:8080/static/js/2.aa56b853.chunk.js:2:1224877

Components:
in td
in Cell
in tr
in BodyRow
in tbody
in Unknown
in table
in div
in div
in Unknown
in Unknown
in div
in Ne
in div
in div
in f
in div
in Er
in div
in x
in div
in w
in div
in a
in div
in ForwardRef
in a
in t
in t
in Pi
in ki
in Zi
in a
in main
in j
in Content
in section
in n
in Layout
in s
in section
in n
in Layout
in t
in t
in a
in a
in t
in t

Environment:
NODE_ENV : production
GIT_SHA  : a89848367df0c94cee64aa15345ed720fb17e83e
GIT_REF  : v1.2.1
TIMESTAMP: 1605538980
appName  : Kowl


```

**Comment by MigTremblay** [comment]
Turn out I was not up to date and this issue has been fixed in another version
