### ISSUE TITLE
Rendering error: Backend reported new/unknown endpoints for endpointCompatibility: "DELETE /api/topics/{topicName}/records"

### ISSUE THREAD

**Issue by s-prosvirnin** [cloudhut/kowl#295]
Message:
Backend reported new/unknown endpoints for endpointCompatibility:
"DELETE /api/topics/{topicName}/records"

Stack (Decoded):
render (components/App.tsx:395:18)
allowStateChanges<T> (../../src/core/action.ts:149:15)
reactiveRender (../../src/observerClass.ts:134:28)
Array (../../src/core/derivation.ts:177:21)
isSpyEnabled (../../src/core/reaction.ts:137:23)
reactiveRender (../../src/observerClass.ts:132:8)
qi (../node_modules/react-dom/cjs/react-dom.production.min.js:187:187)
pi (../node_modules/react-dom/cjs/react-dom.production.min.js:186:172)
a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch (../node_modules/react-dom/cjs/react-dom.production.min.js:269:426)
Pj (../node_modules/react-dom/cjs/react-dom.production.min.js:250:346)

Stack (Raw):
at n.value (http://localhost:8084/static/js/main.003a3ce2.chunk.js:1:467834)
    at Le (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:13429)
    at http://localhost:8084/static/js/2.a0e88877.chunk.js:2:63503
    at Xe (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:19362)
    at e.t.track (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:23698)
    at n.l [as render] (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:63468)
    at Hi (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:1492321)
    at Vi (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:1492118)
    at $s (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:1533221)
    at _l (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:1519322)

Components:

    at n (http://localhost:8084/static/js/main.003a3ce2.chunk.js:1:467703)
    at n (http://localhost:8084/static/js/main.003a3ce2.chunk.js:1:433581)
    at n (http://localhost:8084/static/js/main.003a3ce2.chunk.js:1:465509)
    at t (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:118479)
    at t (http://localhost:8084/static/js/2.a0e88877.chunk.js:2:348858)

Environment:
NODE_ENV       : production
GIT_SHA        : 33a5de35c15702914ab66bc0d623b75461f93a9c
GIT_REF        : master
TIMESTAMP      : 1639513151
BUILT_FROM_PUSH: true
appName        : Kowl

**Comment by weeco** [comment]
https://github.com/cloudhut/kowl/commit/645e3b4d55aeb7d7459491c4cfd5a5f42c61239e
