### ISSUE TITLE
Type Error while accessing group page

### ISSUE THREAD

**Issue by tajpouria** [cloudhut/kowl#297]
```
Type:
TypeError

Message:
Cannot read properties of null (reading 'length')

Stack (Decoded):
render (components/pages/consumers/Group.Details.tsx:120:102)
sum (utils/arrayExtensions.ts:113:43)
sum (utils/arrayExtensions.ts:113:16)
render (components/pages/consumers/Group.Details.tsx:120:76)
allowStateChanges<T> (../../src/core/action.ts:149:15)
reactiveRender (../../src/observerClass.ts:134:28)
Array (../../src/core/derivation.ts:177:21)
isSpyEnabled (../../src/core/reaction.ts:137:23)
reactiveRender (../../src/observerClass.ts:132:8)

Stack (Raw):
TypeError: Cannot read properties of null (reading 'length')
    at http://localhost:8080/static/js/main.fb260068.chunk.js:1:288049
    at http://localhost:8080/static/js/main.fb260068.chunk.js:1:18174
    at Array.reduce (<anonymous>)
    at Array.sum (http://localhost:8080/static/js/main.fb260068.chunk.js:1:18143)
    at n.value (http://localhost:8080/static/js/main.fb260068.chunk.js:1:288010)
    at Le (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:13429)
    at http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:63503
    at Xe (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:19362)
    at e.t.track (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:23698)
    at n.l [as render] (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:63468)

Components:

    at n (http://localhost:8080/static/js/main.fb260068.chunk.js:1:285890)
    at t (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:121185)
    at t (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:122136)
    at u (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:960844)
    at m (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:961553)
    at Wi
    at n (http://localhost:8080/static/js/main.fb260068.chunk.js:1:422561)
    at main
    at m (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:603978)
    at a (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:603808)
    at section
    at http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:604238
    at a (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:603808)
    at l (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:59792)
    at section
    at http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:604238
    at a (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:603808)
    at t (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:121185)
    at t (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:122136)
    at n (http://localhost:8080/static/js/main.fb260068.chunk.js:1:433867)
    at n (http://localhost:8080/static/js/main.fb260068.chunk.js:1:465795)
    at t (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:118479)
    at t (http://localhost:8080/static/js/2.dd509dcb.chunk.js:2:348858)

Environment:
NODE_ENV       : production
GIT_SHA        : 7a5cc04d213bd1201b0c78c3eaa019f14e40fb22
GIT_REF        : master
TIMESTAMP      : 1639836489
BUILT_FROM_PUSH: true
appName        : Kowl

Location:
Protocol: http:
Path    : /groups/hb-inbox-client
Search  : 
Hash    : 
```

**Comment by weeco** [comment]
Hey @tajpouria ,
thanks for reporting this. Could you also provide the JSON response that is sent from the backend to the frontend for the given request? You can inspect that within the network tab in case you use chrome.

**Comment by tajpouria** [comment]
```json
{
  "consumerGroup": {
    "groupId": "hb-inbox-client",
    "state": "Stable",
    "protocolType": "consumer",
    "protocol": "RoundRobinByTime",
    "members": [
      {
        "id": "client",
        "clientId": "client",
        "clientHost": "/127.0.0.6",
        "assignments": [
          {
            "topicName": "123reply",
            "partitionIds": null
          }
        ]
      },
      {
        "id": "client",
        "clientId": "client",
        "clientHost": "/127.0.0.6",
        "assignments": [
          {
            "topicName": "456reply",
            "partitionIds": [
              0
            ]
          }
        ]
      }
    ],
    "coordinatorId": 0,
    "topicOffsets": [],
    "allowedActions": null
  }
}
```

```json
{
  "endpointCompatibility": {
    "kafkaVersion": "v3.0",
    "endpoints": [
      {
        "endpoint": "/api/cluster/config",
        "method": "GET",
        "isSupported": true
      },
      {
        "endpoint": "/api/consumer-groups",
        "method": "GET",
        "isSupported": true
      },
      {
        "endpoint": "/api/consumer-groups/{groupId}",
        "method": "PATCH",
        "isSupported": true
      },
      {
        "endpoint": "/api/consumer-groups/{groupId}",
        "method": "DELETE",
        "isSupported": true
      },
      {
        "endpoint": "/api/operations/reassign-partitions",
        "method": "GET",
        "isSupported": true
      },
      {
        "endpoint": "/api/operations/reassign-partitions",
        "method": "PATCH",
        "isSupported": true
      }
    ]
  }
}
```

**Comment by tajpouria** [comment]
I guess it case by null `partitionIds`, 
is that any stable version available @weeco ??

**Comment by weeco** [comment]
Hm I'm unsure if this is the reason but I pinged @rikimaru0345 to have a look. I think we haven't changed anything on that part for a longer time, but of course you can try v1.5.0 which is used across many deployments and we haven't heard about that issue yet. Might be something that is very specific to your environment.

Other than that you are usually good to use the latest version of master which you did according to the stack trace.

**Comment by tajpouria** [comment]
@weeco I tried both Master and 1.5.0 
Issue exists there thank u anyway

**Comment by rikimaru0345** [comment]
I'll take care of it. Should be an easy fix. 👍

**Comment by rikimaru0345** [comment]
It's actually a bug in the backend @weeco will take care of it.

**Comment by weeco** [comment]
I pushed a fix for that and I'll close the issue for now. Let me know if you still have issues after you've tried the latest version :)

**Comment by tajpouria** [comment]
@rikimaru0345 @weeco it resolved the issue, thank u guys ❤️
