### ISSUE TITLE
Unable to check if feature "GET /api/quotas" 

### ISSUE THREAD

**Issue by justinporter73** [cloudhut/kowl#306]
Message:
Unable to check if feature "GET /api/quotas" is supported because the backend did not return any information about it.

Stack (Decoded):
render (components/App.tsx:396:18)
allowStateChanges<T> (../../src/core/action.ts:149:15)
reactiveRender (../../src/observerClass.ts:134:28)
Array (../../src/core/derivation.ts:177:21)
isSpyEnabled (../../src/core/reaction.ts:137:23)
reactiveRender (../../src/observerClass.ts:132:8)
qi (../node_modules/react-dom/cjs/react-dom.production.min.js:187:187)
pi (../node_modules/react-dom/cjs/react-dom.production.min.js:186:172)
a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch (../node_modules/react-dom/cjs/react-dom.production.min.js:269:426)
Pj (../node_modules/react-dom/cjs/react-dom.production.min.js:250:346)

Stack (Raw):
at n.value (https://kowl.test.pr100.mastermindtms.com/static/js/main.308f10ec.chunk.js:1:473614)
    at Le (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:13429)
    at https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:63503
    at Xe (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:19362)
    at e.t.track (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:23698)
    at n.l [as render] (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:63468)
    at Hi (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:1492888)
    at Vi (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:1492685)
    at $s (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:1533788)
    at _l (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:1519889)

Components:

    at n (https://kowl.test.pr100.mastermindtms.com/static/js/main.308f10ec.chunk.js:1:473483)
    at n (https://kowl.test.pr100.mastermindtms.com/static/js/main.308f10ec.chunk.js:1:439344)
    at n (https://kowl.test.pr100.mastermindtms.com/static/js/main.308f10ec.chunk.js:1:471272)
    at t (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:118479)
    at t (https://kowl.test.pr100.mastermindtms.com/static/js/2.4e3a39ca.chunk.js:2:349283)

Environment:
NODE_ENV        : production
GIT_SHA         : 0e7d7d546ee20b5c395d1350b5244d75f478dd81
GIT_REF         : master
TIMESTAMP       : 1641946412
BUSINESS_GIT_SHA: 763b551c45508c3a44d4a0529f8c4dc63290e448
BUSINESS_GIT_REF: master
BUILT_FROM_PUSH : true
BUSINESS        : true
appName         : Kowl Business

Location:
Protocol: https:
Path    : /topics
Search  : 
Hash    :

**Comment by weeco** [comment]
@justinporter73 I believe that is a version mismatch between the frontend and backend (of Kowl Business) in this case. I've just trigerred a new release with an update Kowl dependency that should hopefully fix it. Builds take roughly ~6minutes, so expect a new docker image version to be appear here: https://quay.io/repository/cloudhut/kowl-business?tag=latest&tab=tags within the next few minutes.

Please let me know if the issue persists with the new version 👍

**Comment by justinporter73** [comment]
Just an FYI we used the new master and it still presented the same error.  Once we changed the tag to latest, we were able to login again.

**Comment by weeco** [comment]
Hey @justinporter73 ,
just to make sure before diving into it: You used `master-8e05318` and not `master` as tag (which might be cached at your kubernetes node and refers to a previous version you had pulled before). Is that correct?

**Comment by justinporter73** [comment]
That was it we tagged with `master-8e05318` and everything worked as expected.  Thank you

**Comment by weeco** [comment]
Awesome thanks for letting me know and reaching out. Let me know if you want to have more seats 🚀
